<?php
/*
        pfBlockerNG_import.php

        pfBlockerNG
        Copyright (C) 2014 BBcan177@gmail.com
        All rights reserved.

        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:

        1. Redistributions of source code must retain the above copyright notice,
                 this list of conditions and the following disclaimer.

        2. Redistributions in binary form must reproduce the above copyright
                 notice, this list of conditions and the following disclaimer in the
                 documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
        INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
        AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
        AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
        OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
        SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
        INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
        CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
        ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
        POSSIBILITY OF SUCH DAMAGE.

*/

require_once("config.inc");
require_once("util.inc");
require_once("functions.inc");
require_once("pkg-utils.inc");
require_once("pfsense-utils.inc");
require_once("globals.inc");
require_once("services.inc");

print "<pre>";
$pfblist_new = array ( array ( 	"none" => "", 
				"aliasname" => "IBlock",
				"description" => "pfBlockerNG IBlock",
				"infolists" => "",
				"row" => array (array ("format"	=> "gz",
							"state"	=> "Disabled",
							"url"	=> "http://list.iblocklist.com/?list=usrcshglbiilevmyfhse&amp;fileformat=p2p&amp;archiveformat=gz",
							"header"=> "IBlock_BT_Hijack"),
						array ("format" => "gz",
							"state"	=> "Disabled",
							"url"	=> "http://list.iblocklist.com/?list=ficutxiwawokxlcyoeye&amp;fileformat=p2p&amp;archiveformat=gz",
							"header"=> "IBlock_BT_FS"),
						array ("format" => "gz",
							"state"	=> "Disabled",
							"url"	=> "http://list.iblocklist.com/?list=ghlzqtqxnzctvvajwwag&amp;fileformat=p2p&amp;archiveformat=gz",
							"header"=> "IBlock_BT_Web"),
						array ("format" => "gz",
							"state"	=> "Disabled",
							"url"	=> "http://list.iblocklist.com/?list=llvtlsjyoyiczbkjsxpf&amp;fileformat=p2p&amp;archiveformat=gz",
							"header"=> "IBlock_BT_Spy"),
						array ("format" => "gz",
							"state"	=> "Disabled",
							"url"	=> "http://list.iblocklist.com/?list=cwworuawihqvocglcoss&amp;fileformat=p2p&amp;archiveformat=gz",
							"header"=> "IBlock_Badpeer"),
						array ("format" => "gz",
							"state"	=> "Disabled",
							"url"	=> "http://list.iblocklist.com/?list=dgxtneitpuvgqqcpfulq&fileformat=p2p&archiveformat=gz",
							"header"=> "IBlock_Ads"),
						array ("format" => "gz",
							"state"	=> "Disabled",
							"url"	=> "http://list.iblocklist.com/?list=xoebmbyexwuiogmbyprb&amp;fileformat=p2p&amp;archiveformat=gz",
							"header"=> "IBlock_Proxy")),
				"action"=> "Disabled",
				"cron"	=> "04hours",
				"dow"	=> "1",
 				"aliaslog" => "enabled",
				"custom"=> "",
				"custom_update" => "disabled"),

		     array (	"none" => "",
				"aliasname" => "PRI1",
				"description" => "pfBlockerNG PRI1",
				"infolists" => "",
				"row" => array (array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "https://rules.emergingthreats.net/blockrules/compromised-ips.txt",
							"header"=> "ET_Comp"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt",
							"header"=> "ET_Block"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "http://www.spamhaus.org/drop/drop.txt",
							"header"=> "Spamhaus_drop"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "http://www.spamhaus.org/drop/edrop.txt",
							"header"=> "Spamhaus_edrop"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "http://cinsscore.com/list/ci-badguys.txt",
							"header"=> "CIArmy"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist",
							"header"=> "Abuse_Zeus"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"	=> "https://spyeyetracker.abuse.ch/blocklist.php?download=ipblocklist",
							"header"=> "Abuse_Spyeye"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"	=> "https://palevotracker.abuse.ch/blocklists.php?download=ipblocklist",
							"header"=> "Abuse_Palevo"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "https://sslbl.abuse.ch/blacklist/sslipblacklist_aggressive.csv",
							"header"=> "Abuse_SSLBL"),
						array ("format"	=> "block",
							"state"	=> "Disabled",
							"url"	=> "https://feeds.dshield.org/block.txt",
							"header"=> "dShield_Block"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "https://labs.snort.org/feeds/ip-filter.blf",
							"header"=> "Snort_BL"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "http://osint.bambenekconsulting.com/feeds/goz-iplist.txt",
							"header"=> "BBC_Goz")),
				"action"=> "Disabled",
				"cron"	=> "01hour",
				"dow"   => "1",
				"aliaslog" => "enabled",
				"custom"=> "",
				"custom_update" => "disabled"),

		     array (    "none" => "",
				"aliasname" => "PRI2",
				"description" => "pfBlockerNG PRI2",
				"infolists" => "",
				"row" => array (array ("format"	=> "gz_2",
							"state"	=> "Disabled",
							"url"	=> "https://reputation.alienvault.com/reputation.snort.gz",
							"header"=> "Alienvault"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "https://atlas.arbor.net/summary/attacks.csv",
							"header"=> "Atlas_Attacks"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "https://atlas.arbor.net/summary/botnets.csv",
							"header"=> "Atlas_Botnets"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "https://atlas.arbor.net/summary/fastflux.csv",
							"header"=> "Atlas_Fastflux"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "https://atlas.arbor.net/summary/phishing.csv",
							"header"=> "Atlas_Phishing"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "https://atlas.arbor.net/summary/scans.csv",
							"header"=> "Atlas_Scans"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "http://www.cyber-ta.org/releases/malware/SOURCES/Attacker.Cumulative.Summary",
							"header"=> "SRI_Attackers"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "http://www.cyber-ta.org/releases/malware/SOURCES/CandC.Cumulative.Summary",
							"header"=> "SRI_CC"),
						array ("format"	=> "html",
							"state"	=> "Disabled",
							"url"	=> "https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1",
							"header"=> "HoneyPot")),
				"action"=> "Disabled",
				"cron"  => "04hours",
				"dow"   => "1",
				"aliaslog" => "enabled",
				"custom"=> "",
				"custom_update" => "disabled"),

		     array (    "none" => "",
				"aliasname" => "PRI3",
				"description" => "pfBlockerNG PRI3",
				"infolists" => "",
				"row" => array (array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "http://www.malwaredomainlist.com/hostslist/ip.txt",
							"header"=> "MDL"),
						array ("format"	=> "txt",
							"state"	=> "Disabled",
							"url"	=> "http://www.nothink.org/blacklist/blacklist_malware_http.txt",
							"header"=> "Nothink_BL"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://www.nothink.org/blacklist/blacklist_ssh_week.txt",
							"header"=> "Nothink_SSH"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://www.nothink.org/blacklist/blacklist_malware_dns.txt",
							"header"=> "Nothink_Malware"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://danger.rulez.sk/projects/bruteforceblocker/blist.php",
							"header"=> "DangerRulez"),
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "https://www.autoshun.org/files/shunlist.csv",
							"header"=> "Shunlist"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://www.infiltrated.net/blacklisted",
							"header"=> "Infiltrated"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://www.dragonresearchgroup.org/insight/sshpwauth.txt",
							"header"=> "DRG_SSH"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://www.dragonresearchgroup.org/insight/vncprobe.txt",
							"header"=> "DRG_VNC"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://www.dragonresearchgroup.org/insight/http-report.txt",
							"header"=> "DRG_HTTP"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://feodotracker.abuse.ch/blocklist/?download=ipblocklist",
							"header"=> "Feodo_Block"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://feodotracker.abuse.ch/blocklist/?download=badips",
							"header"=> "Feodo_Bad"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://www.reputationauthority.org/toptens.php",
							"header"=> "WatchGuard"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://vmx.yourcmc.ru/BAD_HOSTS.IP4",
							"header"=> "VMX"),
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "http://www.geopsy.org/blacklist.html",
							"header"=> "Geopsy"),
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "https://www.maxmind.com/en/anonymous_proxies",
							"header"=> "Maxmind"),
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "http://www.botscout.com/last_caught_cache.htm",
							"header"=> "BotScout"),	
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "https://www.juniper.net/security/auto/spam",
							"header"=> "Juniper"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://blocklist.greensnow.co/greensnow.txt",
							"header"=> "Greensnow"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://lists.blocklist.de/lists/all.txt",
							"header"=> "BlocklistDE"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://www.stopforumspam.com/downloads/toxic_ip_cidr.txt",
							"header"=> "SFS_Toxic")),
				"action"=> "Disabled",
				"cron"  => "04hours",
				"dow"   => "1",
				"aliaslog" => "enabled",
				"custom"=> "",
				"custom_update" => "disabled"),

		     array (    "none" => "",
				"aliasname" => "SEC1",
				"description" => "pfBlockerNG SEC1",
				"infolists" => "",
				"row" => array (array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "http://www.malwaregroup.com/ipaddresses/malicious",
							"header"=> "MalwareGroup"),
						array ("format" => "gz_2",
							"state"	=> "Disabled",
							"url"   => "https://www.openbl.org/lists/base_90days.txt.gz",
							"header"=> "OpenBL"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://malc0de.com/bl/IP_Blacklist.txt",
							"header"=> "Malcode"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://www.badips.com/get/list/any/2",
							"header"=> "BadIPs")),
				"action"=> "Disabled",
				"cron"  => "04hours",
				"dow"   => "1",
				"aliaslog" => "enabled",
				"custom"=> "",
				"custom_update" => "disabled"),

		     array (    "none" => "",
				"aliasname" => "TOR",
				"description" => "pfBlockerNG TOR",
				"infolists" => "",
				"row" => array (array ("format" => "gz",
							"state"	=> "Disabled",
							"url"   => "http://list.iblocklist.com/?list=togdoptykrlolpddwbvz&fileformat=p2p&archiveformat=gz",
							"header"=> "IBlock_Tor"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "https://torstatus.blutmagie.de/ip_list_exit.php/Tor_ip_list_EXIT.csv",
							"header"=> "Blut_Tor"),
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "https://rules.emergingthreats.net/open/suricata/rules/tor.rules",
							"header"=> "ET_Tor")),
				"action"=> "Disabled",
				"cron"  => "04hours",
				"dow"   => "1",
				"aliaslog" => "enabled",
				"custom"=> "",
				"custom_update" => "disabled"),

		     array (    "none" => "",
				"aliasname" => "MAIL",
                                "description" => "pfBlockerNG MAIL",
                                "infolists" => "",
                                "row" => array (array ("format"	=> "txt",
														"state"	=> "Disabled",
                                                        "url"	=> "https://virbl.bit.nl/download/virbl.dnsbl.bit.nl.txt",
                                                        "header"=> "VirBL"),
						array ("format" => "zip",
							"state"	=> "Disabled",
							"url"   => "http://www.stopforumspam.com/downloads/bannedips.zip",
							"header"=> "SFS_All"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://antispam.imp.ch/spamlist",
							"header"=> "Improware"),
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "http://toastedspam.com/denylist.cgi",
							"header"=> "ToastedSpam"),
						array ("format" => "html",
							"state"	=> "Disabled",
							"url"   => "http://rss.uribl.com/reports/7d/dns_a.html",
							"header"=> "URIBL"),
						array ("format" => "txt",
							"state"	=> "Disabled",
							"url"   => "http://spamcop.net/w3m?action=map;net=cmaxcnt;mask=65535;sort=spamcnt;format=text",
							"header"=> "SpamCop"),
						array ("format" => "gz_2",
							"state"	=> "Disabled",
							"url"   => "http://www.dnsbl.manitu.net/download/nixspam-ip.dump.gz",
							"header" => "Nix_Spam")),
				"action"=> "Disabled",
				"cron"  => "08hours",
				"dow"   => "1",
				"aliaslog" => "enabled",
				"custom"=> "",
				"custom_update" => "disabled")
		);


print "Checking for Existing pfBlockerNG Alias/Lists\n";

// Check for Existing pfBlockerNG Allias/Lists
if (is_array($config['installedpackages']['pfblockernglistsv4']['config'])) {
	print "Found existing Alias/Lists. Merging Existing Alias/Lists with Imported Version\n\n"; 
	$pfblist = $config['installedpackages']['pfblockernglistsv4']['config'];
	$pfbfinal = array_merge($pfblist, $pfblist_new);
	$config['installedpackages']['pfblockernglistsv4']['config'] = $pfbfinal;
} else {
	print "No existing Alias/Lists found. Importing new Version.\n\n";
	$config['installedpackages']['pfblockernglistsv4']['config'] = $pfblist_new;
}

print  "pfBlockerNG Alias List Import Completed.";
write_config();

?>
